--
-- View: schema_lock_mdl_info
--
-- Requires plugin metadata_lock_info.so
--

INSTALL SONAME 'metadata_lock_info';

CREATE OR REPLACE
  ALGORITHM = TEMPTABLE
  DEFINER = 'root'@'localhost'
  SQL SECURITY INVOKER 
VIEW schema_lock_mdl_info (
  W_CONN_ID,
  W_SQL_TEXT,
  L_CONN_ID,
  LOCK_MODE,
  LOCK_TYPE,
  TIME,
  USER,
  HOST,
  TABLE_SCHEMA,
  TABLE_NAME
) AS
SELECT
  P.ID AS W_CONN_ID, P.INFO AS W_SQL_TEXT,
  M.THREAD_ID AS L_CONN_ID, M.LOCK_MODE, M.LOCK_TYPE, P.TIME,
  P.USER, P.HOST, M.TABLE_SCHEMA, M.TABLE_NAME
FROM INFORMATION_SCHEMA.PROCESSLIST P, INFORMATION_SCHEMA.METADATA_LOCK_INFO M
WHERE LOCATE(lcase(M.LOCK_TYPE), lcase(P.STATE))>0
  AND M.LOCK_MODE NOT IN ('MDL_SHARED_READ')
;
